"""agent_to_character

Revision ID: 25d6c905c701
Revises: 6138e35e2905
Create Date: 2024-11-07 03:43:57.799009

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "25d6c905c701"
down_revision: Union[str, None] = "6138e35e2905"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "history_logs", sa.Column("character_id", sa.Integer(), nullable=False)
    )
    op.drop_constraint("history_logs_ibfk_1", "history_logs", type_="foreignkey")
    op.create_foreign_key(None, "history_logs", "characters", ["character_id"], ["id"])
    op.drop_column("history_logs", "agent_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "history_logs",
        sa.Column("agent_id", mysql.INTEGER(), autoincrement=False, nullable=False),
    )
    op.drop_constraint(None, "history_logs", type_="foreignkey")
    op.create_foreign_key(
        "history_logs_ibfk_1", "history_logs", "characters", ["agent_id"], ["id"]
    )
    op.drop_column("history_logs", "character_id")
    # ### end Alembic commands ###
