"""modify payment_url

Revision ID: 8464be911010
Revises: 544e35710a2f
Create Date: 2024-12-04 15:08:38.520094

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "8464be911010"
down_revision: Union[str, None] = "544e35710a2f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "payments", sa.Column("checkout_url", sa.String(length=2083), nullable=True)
    )
    op.add_column(
        "payments", sa.Column("qr_code", sa.String(length=2083), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("payments", "qr_code")
    op.drop_column("payments", "checkout_url")
    # ### end Alembic commands ###
