"""remove_f_name_l_name

Revision ID: adff31eb7006
Revises: d507f9351d0c
Create Date: 2024-11-23 14:40:54.768765

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "adff31eb7006"
down_revision: Union[str, None] = "d507f9351d0c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user_accounts", sa.Column("name", sa.String(length=255), nullable=True)
    )
    op.drop_column("user_accounts", "last_name")
    op.drop_column("user_accounts", "first_name")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user_accounts",
        sa.Column("first_name", mysql.VARCHAR(length=255), nullable=True),
    )
    op.add_column(
        "user_accounts",
        sa.Column("last_name", mysql.VARCHAR(length=255), nullable=True),
    )
    op.drop_column("user_accounts", "name")
    # ### end Alembic commands ###
