"""fix_payment_enum_field

Revision ID: cd4617d61496
Revises: 8e7e7999b1be
Create Date: 2024-12-04 20:45:43.501565

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'cd4617d61496'
down_revision: Union[str, None] = '8e7e7999b1be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('payments', 'amount',
               existing_type=mysql.FLOAT(),
               type_=sa.Enum('two_hundred', 'five_hundred', 'one_million', 'two_million', name='order_amount_enum'),
               existing_nullable=False)
    op.alter_column('payments', 'status',
               existing_type=mysql.ENUM('pending', 'completed', 'cancelled'),
               type_=sa.Enum('PENDING', 'PAID', 'CANCELLED', name='order_status_enum'),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('payments', 'status',
               existing_type=sa.Enum('PENDING', 'PAID', 'CANCELLED', name='order_status_enum'),
               type_=mysql.ENUM('pending', 'completed', 'cancelled'),
               existing_nullable=False)
    op.alter_column('payments', 'amount',
               existing_type=sa.Enum('two_hundred', 'five_hundred', 'one_million', 'two_million', name='order_amount_enum'),
               type_=mysql.FLOAT(),
               existing_nullable=False)
    # ### end Alembic commands ###
