"""remove_verified_account

Revision ID: d507f9351d0c
Revises: 25d6c905c701
Create Date: 2024-11-14 00:01:55.428727

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "d507f9351d0c"
down_revision: Union[str, None] = "25d6c905c701"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("username", table_name="user_accounts")
    op.drop_column("user_accounts", "is_verified")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user_accounts",
        sa.Column(
            "is_verified",
            mysql.TINYINT(display_width=1),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.create_index("username", "user_accounts", ["username"], unique=True)
    # ### end Alembic commands ###
